- hosts: myserver
  vars:
          - image: charistha/nginx
  tasks:
          - name: Install python-docker di ubuntu
            apt:
                    name: "{{item}}"
                    state: present
            loop:
                    - python3
                    - python3-docker
            when: ansible_distribution ==  "Ubuntu"

          - name: Instal python-dcioker di centos
            yum:
                    name: "{{item}}"
                    state: present
            loop:
                    - python3
                    - python3-docker
            when: ansible_distribution == "CentOS"

          - name: pull image docker
            docker_image:
                    name: "{{image}}"
                    state: present
                    force: yes

          - name: run container
            docker_container:
                    name : web_server
                    image: "{{image}}"
                    state: started
                    published_port:
                            - 10000:80
                    recreate: yes
